language: go

go:
  - 1.8
  - tip

notifications:
  email: false

go_import_path:
  #/

before_install:
  - mv $HOME/gopath/src/github.com/Sevennn/agenda-go-server $HOME/gopath/src

#install: true

script:
  - cd $HOME/gopath/src/agenda-go-server
  - go test -v ./...
