language: go

go:
  - 1.9
  - tip

notifications:
  email: false

go_import_path:
  #/

before_install:
  - mv $HOME/gopath/src/github.com/Sevennn/github.com/Sevennn/agenda-go-server $HOME/gopath/src
  - go get -t -v github.com/Sevennn/agenda-go-server/service/...
  - cd $HOME/gopath/src/github.com/Sevennn/agenda-go-server

install: true

script:
  - go test -v github.com/Sevennn/agenda-go-server/service/entity
  - go test -v github.com/Sevennn/agenda-go-server/service/loghelper
  # - go test -v github.com/Sevennn/agenda-go-server/service/service

